# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45d91de85d88f64a2b3f59d4f09ba671d8d6567edef7e002d7542db9716c983e0764fa5553676a74ed51c0ee822f05fd3988afec0c7bd907c3f662682e8a408c
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>


test:
  secret_key_base: b46223ba08d78294000ae34055fa62b30c56a727d5159caca32b50becbcd19948ffdfdd94743469e7d169d598ed0516e4c122fe3c15ee93fc7023ced4a50bcb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  